version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mahesh:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springapp
    image: mahesh
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      mysql:
        condition: service_healthy  

networks:
  my-network:
    name: my-network
    driver: bridge
